FROM alpine:3.20

EXPOSE 5200
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/main/" \
  >> /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/community/" \
  >> /etc/apk/repositories \
  && echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing/" \
  >> /etc/apk/repositories \
  && apk update \
  && apk add --update stunnel \
  && rm -rf /tmp/* /var/cache/apk/*
COPY stunnel/entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
COPY certificates/ /certificates/
RUN chmod -R 600 /certificates
ENTRYPOINT ["/bin/entrypoint.sh"]
CMD ["/usr/bin/stunnel", "/etc/stunnel.conf"]
