#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting apply-terraform"
_terraform init -backend-config=config.s3.tfbackend -upgrade
_terraform apply -var-file=vars.tfvars -auto-approve
echo "--> Completed apply-terraform"
