#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting apply-terraform"
_terraform init --upgrade
_terraform apply --var-file=vars.tfvars --auto-approve
echo "--> Completed apply-terraform"
