#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting create-podman-connection"
echo "--> Creating podman connection to traccar server"
# https://github.com/tailscale/tailscale/issues/12409
traccar_server_ip=$(_ssh curl --silent api.ipify.org)
podman system connection remove traccar
# Assumes ssh-agent contains key
podman \
  system \
  connection \
  add \
  traccar \
  "ssh://ubuntu@${traccar_server_ip}/run/user/1000/podman/podman.sock"
echo "--> Completed create-podman-connection"
