#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting deploy-pod"
scp \
  -o StrictHostKeychecking=no \
  traccar.yaml \
  "ubuntu@traccar:/storage/traccar.yaml"
_ssh systemctl --user restart traccar
echo "--> Completed deploy-pod"
