#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/create-podman-connection
podman --connection=traccar build --tag=stunnel --file=stunnel/Containerfile .
podman --connection=traccar kube play --replace "${PODMAN_SECRETS_FILE}"
podman --connection=traccar kube play --replace pod.yaml
