#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

echo "--> Starting deploy-host"
terraform -chdir=terraform init --upgrade
terraform -chdir=terraform apply --var-file="${TF_VARS_FILE}"
echo "--> Completed deploy-host"
