#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting deploy-secrets"
for secret in out/kube/*; do
  _podman kube play --quiet "${secret}"
done
echo "--> Completed deploy-secrets"
