#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/create-podman-connection
podman --connection=traccar kube down "${PODMAN_SECRETS_FILE}"
podman --connection=traccar kube down pod.yaml
