#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source scripts/utils.bash
echo "--> Starting play-secrets"
_podman kube play --quiet <(envsubst < podman/secrets.yaml)
echo "--> Completed play-secrets"
